package com.test.model;

public enum PaymentState {
    PAYMENT_INITIATED,
    PAYMENT_VALIDATED,
    INSUFFICIENT_BALANCE,
    SOURCE_ACCOUNT_DEBITED,
    BENE_ACCOUNT_CREDITED,
    PAYMENT_COMPLETED_SUCESS,
    PAYMENT_COMPLETED_FAILURE
}
